### ISSUE TITLE
[Feature Request] White spaces and Tabs

### ISSUE THREAD

**Issue by GitClickOk** [Projektanker/code-butler#1]
I have 2 suggestions (or requests):

1. Clean up spaces in end of lines;
2. Normalize Tabs to Spaces (or spaces to tabs... but then you will need some way to change settings);

**Comment by just-seba** [comment]
Hi @GitClickOk.
thanks for your feedback.
In my opinion Code Butler should not be seen as a formatter.
The C# formatter of VS Code is already able to 
>  1. Clean up spaces in end of lines;
>  2. Normalize Tabs to Spaces (or spaces to tabs... but then you will need some way to change settings);  

Therefore I added a feature: The VS Code extension will execute the `Format Document` command of VS Code after cleaning the C# file.

In case you are using Code Butler as a command line tool: 
You should check out [dotnet-format](https://github.com/dotnet/format) as it is "is a `code formatter` for `dotnet` that applies style preferences to a project or solution."

I think this way your feature request is fulfilled.
What do you think?

**Comment by GitClickOk** [comment]
I understand @SebastianRumohr 

I just suggested these because you suggested Code Butler as alternative to CodeMaid, and (at least in VS2019) CodeMaid it performs these tasks also.

BTW, congratz for the nice library

**Comment by just-seba** [comment]
Thank you very much 😁 

I understand. In my understanding CodeMaid is performing these tasks by using the Visual Studio formatter as is Code Butler since version 1.1.0.

I look forward to more feedback from you.
