### ISSUE TITLE
Question: Where can I find settings?

### ISSUE THREAD

**Issue by pmahend1** [Projektanker/code-butler#10]
I noticed this extension for VS Code doesnt have any configurable settings.
May I know where can I find those?

Once I come to know I would like to contribute to the repository.

**Comment by just-seba** [comment]
There is only one configuration switch to enable/disable cleanup on save. 
You should find it in the VS Code Settings. 
I would really appreciate your contributions.

**Comment by pmahend1** [comment]
I meant the C# clean-up related settings.
I couldn't find any configuration file in VS Code, do we need to get them from C# console project and add configuration based on that?

**Comment by just-seba** [comment]
Yes. Right now the clean up related configuration is embedded statically in the console project.
They need to be made configurable by command line arguments in order to set them by VS code
