### ISSUE TITLE
Publish extension to OpenVsx (VSCodium) 

### ISSUE THREAD

**Issue by pmahend1** [Projektanker/code-butler#12]
I was wondering if this extension can be published to https://open-vsx.org/ as well which is extension marketplace for VSCodium, a trve OSS editor.

It would just require 2 lines of code in CI and creating a publish token with OpenVSX.

**Comment by just-seba** [comment]
Great idea. I will take a look this week.

**Comment by just-seba** [comment]
https://open-vsx.org/extension/projektanker/code-butler

Done 🥳
