### ISSUE TITLE
Global usings should procede any non-global usings

### ISSUE THREAD

**Issue by pm4rcin** [Projektanker/code-butler#14]
Hi, per [documentation](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/globalusingdirective) "**The global_using_directives, if any, must precede any using_directives.**" Otherwise `dotnet run` throws errors and won't compile. By default code-butler sorts it by name so it has to be changed.

**Comment by just-seba** [comment]
Fixed with Version [2.1.0](https://github.com/Projektanker/code-butler/releases/tag/v2.1.0)

**Comment by pm4rcin** [comment]
Thanks! However it looks like open-vsx has problems. I've even tried to search for any extension in vscodium but there's error 500. Looks like you'll have to rerun the failed workflow when they fix problems on their end.

**Comment by just-seba** [comment]
Yes, I noticed that too. I could not publish the new version there either. I will try again tomorrow.

**Comment by just-seba** [comment]
It is published now.  
https://open-vsx.org/extension/projektanker/code-butler

**Comment by pm4rcin** [comment]
It works! I really appreciate your work. :)
