### ISSUE TITLE
Is it possible to ignore some fields when sorting?

### ISSUE THREAD

**Issue by cantti** [Projektanker/code-butler#15]
Hi,

thank you for the great tool.

The only problem I have is inability to ignore some fields when sorting. I want the id field to be always first in EF entities.

**Comment by just-seba** [comment]
Hi,
thank you for your feedback.  
Right now it's not possible to ignore some fields.  
I'd really like to have an option to disable sorting alphabetically entirely. But I'm really busy right now.

**Comment by cantti** [comment]
No problem, I will be waiting for new features.
