### ISSUE TITLE
Support for GitHub code spaces?

### ISSUE THREAD

**Issue by TrevorPilley** [Projektanker/code-butler#16]
Should this extension work in GitHub code spaces?

When I try it, I get an error `Code Butler: undefined`

**Comment by just-seba** [comment]
I'm not familiar with GitHub code spaces. But I do not expect this extension to work in GitHub code spaces because it needs the .NET runtime to be installed.

**Comment by TrevorPilley** [comment]
The .NET SDK is installed in the code space, it’s running in a container and you access VS Code via the browser - you can see more about it here https://github.com/features/codespaces. It might just be a limitation of how the extension works but would be great if it is possible to make it work 🤞🏼

**Comment by just-seba** [comment]
I checked the code spaces documentation. As far as I understand, Code Butler should also work in code spaces. Unfortunately, I don't currently have the capacity to investigate the problem further. Is there any chance that you could take a closer look?

**Comment by just-seba** [comment]
Should be fixed with [just-seba.vscode-code-butler](https://marketplace.visualstudio.com/items?itemName=just-seba.vscode-code-butler).
