### ISSUE TITLE
Invalid output when using the C# 11 required keyword

### ISSUE THREAD

**Issue by TrevorPilley** [Projektanker/code-butler#17]
Running clean up version 2.1.0 against the following:

```csharp
public class Test
{
    public required string Name { get; set; }
}
```

Results in this invalid result:

```csharp
public class Test
{
    string Name { get; set; }
    public required
}
```

Appears to be a similar problem to #13

**Comment by just-seba** [comment]
Fixed with [version 2.2.0](https://github.com/Projektanker/code-butler/releases/tag/v2.2.0)
