### ISSUE TITLE
Clean up misplaces linebreak

### ISSUE THREAD

**Issue by TrevorPilley** [Projektanker/code-butler#18]
Running clean up version 2.1.0 against the following:

```csharp
public class Test
{
    internal static Test Foo { get; set; }

    public Test()
    {        
    }
}
```

Results in

```csharp
public class Test
{

    public Test()
    {
    }
    internal static Test Foo { get; set; }
}
```

Note the line break should be between the closing `}` of the constructor and the property

**Comment by just-seba** [comment]
This is beyond Code Butlers capabilities. The VS code extension executes `Format Document` after the cleanup. It is the responsibility of the formatter to insert a line break after the closing `}`.
