### ISSUE TITLE
Doesnt work unless started from terminal

### ISSUE THREAD

**Issue by pmahend1** [Projektanker/code-butler#9]
This extension does not work unless VS Code is started from terminal.

Need to figure out a way to elevate access when opened directly.

**Comment by just-seba** [comment]
That's odd. Are there any error messages? Which version of VS code and Code Butler are you using?

**Comment by pmahend1** [comment]
I didnt see any error alert or message in the log.
I am on latest System level installed VSCode/VSCodium with latest Code butler.

This is same thing with Omnisharp C# extension which doesnt run unless VS Code opened from terminal , I found out that there.

**Comment by just-seba** [comment]
It seems there is nothing wrong with Code Butler but with your installation of VS Code 🤔
What do you think?

**Comment by pmahend1** [comment]
I don't think there is anything wrong with installation since I did not custom built the VS Code.

Can you try with system installer at your end. 

It would be good to use Electron-Edge-JS to mitigate this,  but one drawback is we need to rebuild and release extension whenever there is a change in electron version.

**Comment by just-seba** [comment]
I tried and it works on my end.

**Comment by pmahend1** [comment]
Alright. I will try to get reproduction steps.

**Comment by pmahend1** [comment]
It doesn't seem to be an issue anymore.
I will flag it if it recurs.
